replicaCount: 1

service:
  type: ClusterIP

resources:
  requests:
    memory: 500Mi
    cpu: 500m
  limits:
    memory: 1Gi
    cpu: 1000m

secrets:
  withingsClientId: AgCzpeHVxnGlvtaLLXE5d4jvAyZZQ+E4UUGY+L0UbsGmW9eThd4BuTyJ6RAJw8aeC474F9RAakpbOI6zqMY4w7YaVNUeBA+RfEew5cGmKMizHI/ExVCq2xVdmO0HwXpweN1ZhpM2JhoUeLMguQ4mMoy7jzNc+ngY82w5I6DBSDixeTi0LTAqLP13CYeCz/Ao4i1kTkrW92gy1pLezUf3HMW2Fp3uxNn+QK3W11yU9XvhCpNzAnir8ShTYiWdG1v4uTNWQKtakXpAJj6R0ht8pLWlAPei+6/LnyTHx/1g7V3d66h8kPVcUkbDL4AhMCi6cES5tjQlaymJ5UyinEgiFkqRi7EtZwGUAFKPP7mbxO9BctYNKXETw2aJ0UTTR23LDkGlsJmp7huGPyzyu3BLfkJySaZnpmJjr+kvgw3+dgT/Q1TJQI1vzMzc42NmMSilJR/ai+Z8OjpJCRB50xpSp1KI8AXm9f8NCObCOlqeNzUcq9caqYxzO5PVOM9hEJZdes7zh21rxgreoLmqclhA5kTk0W61liMbzCUgJTQfC03QAkw3rvk96SIzkZ3EEUMY82Q2GO+5OBNwF7mht7BDWbpn3s+f91Zl8rMR1L5lYrSw3DTVDBzLiU82oO0qdlyylAhkSX06Xso0Ff6iuNH7h9/ST03OH6yO9iQzy82xV4ker9B3yg/Y7hPApgQ0nLidhnxb4xUzDUk73tReXQBvmy7/6vICAE+p4KqmOxuqufSM5lot6w+/XbvZPK8AgbmHYObtEnuVd8xC/0T0m3MURqM6
  withingsClientSecret: AgBH8Zpsxe0OZ0NaqikI1gdIPX60c2Eek2Wbwd3PVcznFQkj74KSS/FvoBGA2NOFd+TImZMBiQ2yrVfA8Z2bdVHXCBLgWLWrDPSdfP4MHMlXMrY3wAX0WYfCW+fPuzHx6cd9rptFDeN21e6NOAFNsX0hOMKXQuXJFSD1B31Dsp0NaF+1LpzXSPSZZDPucmIRd2B9yFfa3pt2Q5kH5+zRaZQnW9iwB0KXXaEyo6h14PR10AU6N/iQsyiHKeIb+rrcRtObFzilR+3gDBo4vbz8qIjzSWk9HKu5Oos30jj++Un0h9FySVVUreXUrgItYoUtZeE4Ec5UVdz8GcrMlHD3J0N8XwybThAw8kiFD9/udZwhmJuq1ZK9UFbCJZKCWCyRmaxvwrXdX+utVPPRejzOFYB+ST0PK9H18ZkoTPAyaPB4YIFB4SS8QPfo+VOFrOF9PHOGh6n9Be6p25LMz/d1lhAlZ98O4KnqPConrEF5ZYOlcafbEwm4EY1fnD2ogmRY9s+wHbhLLq7N/ZwVif7s5XzX+TTl6g+HHLiUhvQgXAEyjUkkMnrR8e4aLnxmXpZgz+Irxzpqq86Il3/h4kxk+Y1I8KFSZ2BRDL9PuC99WTzAzR4FHJam28IO5NDBEBYrYK4bg/ErlfvW/jXnuUvcF3RrrM2poeEXvgfGRSXdarX8Tk/zOxaPIBSjhP2wTLpHwkRyIkA5kx1zVwftRPbh04NS+AUnd7/HK+aIjhANuu2wfzALy7min5ATaIU1hbLYUHYTNR2kxVboSgMlE0ymYi0X
