version: "3.9"
services:
  mysql:
    build: 
      context: ./
      dockerfile: ./database/Dockerfile
    ports:
      - 3307:3306
    env_file:
      - server/.env
    environment:
      - MYSQL_USER=
      - MYSQL_PASSWORD=
  api:
    env_file:
      - server/.env
    environment:
      - MYSQL_HOST=mysql
    build: ./server
    ports:
      - "8080:8080"
  app:
    build: ./client
    environment:
      # For debugging server: API_INTERNAL_HOST: host.docker.internal
      API_INTERNAL_HOST: api
      API_EXTERNAL_HOST: localhost
      API_INTERNAL_PORT: 8080
      API_EXTERNAL_PORT: 3000
    ports:
      - "3000:80"