- name: Provision
  gather_facts: false
  hosts: cluster
  vars:
    is_ci: "{{ lookup('ansible.builtin.env', 'CI') }}"
  vars_files:
    - ../vars/vault.yaml
    - ../vars/defaults.yaml
  roles:
    - role: mucsi96.kubetools.ssh_auth
    - role: mucsi96.kubetools.gather_facts
    - role: mucsi96.kubetools.pull_kube_config
      vars:
        local_kube_config: "{{ inventory_dir }}/.kube/config"
    - role: mucsi96.kubetools.deploy_postgres_db
      vars:
        k8s_name: "{{ db_host }}"
        host_prefix: workout
    - role: mucsi96.kubetools.deploy_spring_app
      vars:
        k8s_name: spring-app
        image: mucsi96/training-log-pro-server
        tag_prefix: server
        host_prefix: workout
        base_path: /api
        app_env:
          POSTGRES_DB: "{{ db_name }}"
          POSTGRES_HOSTNAME: "{{ db_host }}"
          POSTGRES_PORT: "{{ db_port }}"
          POSTGRES_USER: "{{ db_username }}"
          POSTGRES_PASSWORD: "{{ db_password }}"
          WITHINGS_ACCOUNTS_URI: "{{ withings_accounts_uri }}"
          WITHINGS_API_URI: "{{ withings_api_uri }}"
          WITHINGS_CLIENT_ID: "{{ withings_client_id }}"
          WITHINGS_CLIENT_SECRET: "{{ withings_client_secret }}"
    - role: mucsi96.kubetools.deploy_client_app
      vars:
        k8s_name: client-app
        image: mucsi96/training-log-pro-client
        tag_prefix: client
        host_prefix: workout
        base_path: /
