- name: Provision
  gather_facts: false
  hosts: cluster
  vars:
    is_ci: "{{ lookup('ansible.builtin.env', 'CI') }}"
  vars_files:
    - ../vars/vault.yaml
    - ../vars/defaults.yaml
  roles:
    - role: mucsi96.ansible_roles.ssh_auth
    - role: mucsi96.ansible_roles.gather_facts
    - role: mucsi96.ansible_roles.pull_kube_config
      vars:
        local_kube_config: "{{ inventory_dir }}/.kube/config"
    - role: mucsi96.ansible_roles.deploy_postgres_db
      vars:
        k8s_name: "{{ db_host }}"
