{{- $fullName := include "app.fullname" . -}}
{{ $managementPort := required "Missing service.managementPort value" .Values.service.managementPort -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu }}
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}
        ports:
        - name: http
          containerPort: 8080
        - name: management
          containerPort: {{ $managementPort }}
        env:
          - name: MESSAGE
            valueFrom:
              configMapKeyRef:
                name: {{ $fullName }}
                key: message
          - name: MYSQL_DATABASE
            value: {{ required "Missing database.name value" .Values.database.name }}
          - name: MYSQL_HOST
            value: {{ required "Missing database.host value" .Values.database.host }}
          - name: MYSQL_PORT
            value: {{ required "Missing database.port value" .Values.database.port | quote }}
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: {{ $fullName }}
                key: userName
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ $fullName }}
                key: password
          - name: MANAGEMENT_SERVER_PORT
            value: {{ $managementPort | quote }}
          - name: ADMIN_SERVER_HOST
            value: {{ required "Missing adminServer.host value" .Values.adminServer.host }}
          - name: ADMIN_SERVER_PORT
            value: {{ required "Missing adminServer.port value" .Values.adminServer.port | quote }}
          - name: K8S_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: {{ $managementPort }}
          initialDelaySeconds: 15
        startupProbe:
          httpGet:
            path: /actuator/health/liveness
            port: {{ $managementPort }}
          initialDelaySeconds: 15
          failureThreshold: 30
        lifecycle:
          preStop:
            exec:
              command: ["sh", "-c", "sleep 10"]