{{- $fullName := include "app.fullname" . -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ $fullName }}-sealed
  labels:
    {{- include "app.labels" . | nindent 4 }}
  annotations:
    sealedsecrets.bitnami.com/cluster-wide: "true"
spec:
  encryptedData:
    withingsClientId: {{ required "Missing secrets.withingsClientId value" .Values.secrets.withingsClientId }}
    withingsClientSecret: {{ required "Missing secrets.withingsClientSecret value" .Values.secrets.withingsClientSecret }}
    googleClientId: {{ required "Missing secrets.googleClientId value" .Values.secrets.googleClientId }}
    googleClientSecret: {{ required "Missing secrets.googleClientSecret value" .Values.secrets.googleClientSecret }}