{{- $fullName := include "app.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  userName: {{ required "Missing database.userName value" .Values.database.userName | b64enc }}
  password: {{ required "Missing database.password value" .Values.database.password | b64enc }}