{{- $fullName := include "app.fullname" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}
  labels:
    scrape: "spring-boot"
    {{- include "app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ required "Missing service.port value" .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ required "Missing service.managementPort value" .Values.service.managementPort }}
      targetPort: management
      protocol: TCP
      name: management
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}