openapi: '3.0.2'
info:
  title: API
  version: '1.0'

servers:
  - url: http://localhost:8080

paths:

  /withings/weight:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                title: WeightResponse
                type: object
                required:
                  - weight
                properties:
                  weight:
                    type: number
                    format: double

