server:
  forward-headers-strategy: framework
  shutdown: graceful
spring:
  security:
    oauth2:
      client:
        provider:
          withings:
           authorization-uri: https://account.withings.com/oauth2_user/authorize2
           token-uri: https://wbsapi.withings.net/v2/oauth2
        registration:
          withings-client:
            provider: withings
            client-id: ${WITHINGS_CLIENT_ID}
            client-secret: ${WITHINGS_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/authorize/oauth2/code/{registrationId}"
            scope: user.metrics
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOSTNAME}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
management:
  server:
    port: ${SPRING_ACTUATOR_PORT}
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
logging:
  level:
    com:
      zaxxer:
        hikari: OFF
