k8s_namespace: training-log-pro
auth_middelware_name: auth
auth_middelware_namespace: authelia
db_name: training-log-pro
db_host: postgres-db
db_port: 5432
db_username: "{{ lookup('ansible.builtin.password', '/dev/null length=12 chars=ascii_lowercase', seed='{{ inventory_hostname }}-db-username') }}"
db_password: "{{ lookup('ansible.builtin.password', '/dev/null length=20', seed='{{ inventory_hostname }}-db-password') }}"
spring_admin_server_name: spring-boot-admin-server
spring_admin_server_namespace: monitoring
spring_admin_server_port: 9090
db_backup_bucket: training-log-pro-backup
db_backup_exclude_tables:
  - oauth2_authorized_client
db_backup_region: us-east-1
withings_api_uri: https://wbsapi.withings.net
