version: '3.8'

volumes:
  postgres-data:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    environment:
      DOCKER_NETWORK: training-log-pro_devcontainer_default
      TESTCONTAINERS_RYUK_DISABLED: true
      POSTGRES_HOSTNAME: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: training-log
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      SPRING_ACTUATOR_PORT: 8081
      SPRING_ADMIN_SERVER_HOST: localhost
      SPRING_ADMIN_SERVER_PORT: 9090
      WITHINGS_API_URI: https://wbsapi.withings.net
    env_file:
      - .env

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

  db:
    image: postgres:15.2-bullseye
    restart: unless-stopped
    environment:
      POSTGRES_DB: training-log
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
