version: '3.8'

volumes:
  postgres-data:

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    environment:
      POSTGRES_HOSTNAME: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: training-log
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      SPRING_ACTUATOR_PORT: 8081
      SPRING_ADMIN_SERVER_HOST: localhost
      SPRING_ADMIN_SERVER_PORT: 9090
      WEBDRIVER_API_URI: http://chrome:4444/wd/hub
      WITHINGS_ACCOUNTS_URI: https://account.withings.com
      WITHINGS_API_URI: https://wbsapi.withings.net
      STRAVA_API_URI: https://www.strava.com
    env_file:
      - .env

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

  db:
    image: postgres:15.2-bullseye
    restart: unless-stopped
    environment:
      POSTGRES_DB: training-log
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres

  pdadmin:
    image: dpage/pgadmin4:7.5
    restart: unless-stopped
    ports:
      - 5532:80
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@mycomp.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    volumes:
      - ./pgadmin-servers.json:/pgadmin4/servers.json
      - ./pgadmin.pgpass:/tmp/pgpass
    entrypoint: >
      /bin/sh -c "
      chmod 600 /tmp/pgpass;
      /entrypoint.sh;
      "

  chrome:
    image: seleniarm/standalone-chromium:116.0-chromedriver-116.0-grid-4.10.0-20230828
    restart: unless-stopped
    shm_size: '2gb'
