{{- $fullName := include "app.fullname" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
data: 
  initdb.sql: |
    CREATE TABLE oauth2_authorized_client (
      access_token_value blob NOT NULL
    );