{{- $fullName := include "app.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  rootPassword: {{ required "Missing rootPassword value" .Values.rootPassword | b64enc }}
  userName: {{ required "Missing userName value" .Values.userName | b64enc }}
  password: {{ required "Missing password value" .Values.password | b64enc }}