{{- $fullName := include "app.fullname" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
data:
  rootPassword: {{ required "Missing rootPassword value" .Values.rootPassword | b64enc }}
  username: {{ required "Missing username value" .Values.username | b64enc }}
  password: {{ required "Missing password value" .Values.password | b64enc }}
  exporterUsername: {{ required "Missing exporterUsername value" .Values.exporterUsername | b64enc }}
  exporterPassword: {{ required "Missing exporterPassword value" .Values.exporterPassword | b64enc }}