name: CI

on:
  push:
    branches:
      - main

concurrency:
  group: any
  cancel-in-progress: true

jobs:
  test-server:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: server
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "maven"
      - run: mvn test

  test-client:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "yarn"
          cache-dependency-path: client/yarn.lock
      - run: yarn --frozen-lockfile
      - run: yarn test:ci

  build-images:
    needs:
      - test-server
      - test-client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get Ansible Vault key
        run: |
          mkdir .ansible
          echo "${{ secrets.ANSIBLE_VAULT_KEY }}" > .ansible/vault_key

      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip" # caching pip dependencies
      - run: pip install -r requirements.txt

      - uses: buildpacks/github-actions/setup-pack@v5.0.0

      - run: python scripts/build.py ${{ secrets.GITHUB_TOKEN }}

  deploy:
    needs: build-images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get Ansible Vault key
        run: |
          mkdir .ansible
          echo "${{ secrets.ANSIBLE_VAULT_KEY }}" > .ansible/vault_key

      - name: Install Python requirements
        run: pip install -r requirements.txt
